# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BCQGatherOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BCQGatherOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBCQGatherOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BCQGatherOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x49\x52\x30", size_prefixed=size_prefixed)

    # BCQGatherOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BCQGatherOptions
    def InputHiddenSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BCQGatherOptions
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BCQGatherOptionsStart(builder):
    builder.StartObject(2)

def Start(builder):
    BCQGatherOptionsStart(builder)

def BCQGatherOptionsAddInputHiddenSize(builder, inputHiddenSize):
    builder.PrependInt32Slot(0, inputHiddenSize, 0)

def AddInputHiddenSize(builder, inputHiddenSize):
    BCQGatherOptionsAddInputHiddenSize(builder, inputHiddenSize)

def BCQGatherOptionsAddAxis(builder, axis):
    builder.PrependInt32Slot(1, axis, 0)

def AddAxis(builder, axis):
    BCQGatherOptionsAddAxis(builder, axis)

def BCQGatherOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return BCQGatherOptionsEnd(builder)


class BCQGatherOptionsT(object):

    # BCQGatherOptionsT
    def __init__(self):
        self.inputHiddenSize = 0  # type: int
        self.axis = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bcqgatherOptions = BCQGatherOptions()
        bcqgatherOptions.Init(buf, pos)
        return cls.InitFromObj(bcqgatherOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bcqgatherOptions):
        x = BCQGatherOptionsT()
        x._UnPack(bcqgatherOptions)
        return x

    # BCQGatherOptionsT
    def _UnPack(self, bcqgatherOptions):
        if bcqgatherOptions is None:
            return
        self.inputHiddenSize = bcqgatherOptions.InputHiddenSize()
        self.axis = bcqgatherOptions.Axis()

    # BCQGatherOptionsT
    def Pack(self, builder):
        BCQGatherOptionsStart(builder)
        BCQGatherOptionsAddInputHiddenSize(builder, self.inputHiddenSize)
        BCQGatherOptionsAddAxis(builder, self.axis)
        bcqgatherOptions = BCQGatherOptionsEnd(builder)
        return bcqgatherOptions
