# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

class BuiltinOptions(object):
    NONE = 0
    Conv2DOptions = 1
    DepthwiseConv2DOptions = 2
    ConcatEmbeddingsOptions = 3
    LSHProjectionOptions = 4
    Pool2DOptions = 5
    SVDFOptions = 6
    RNNOptions = 7
    FullyConnectedOptions = 8
    SoftmaxOptions = 9
    ConcatenationOptions = 10
    AddOptions = 11
    L2NormOptions = 12
    LocalResponseNormalizationOptions = 13
    LSTMOptions = 14
    ResizeBilinearOptions = 15
    CallOptions = 16
    ReshapeOptions = 17
    SkipGramOptions = 18
    SpaceToDepthOptions = 19
    EmbeddingLookupSparseOptions = 20
    MulOptions = 21
    PadOptions = 22
    GatherOptions = 23
    BatchToSpaceNDOptions = 24
    SpaceToBatchNDOptions = 25
    TransposeOptions = 26
    ReducerOptions = 27
    SubOptions = 28
    DivOptions = 29
    SqueezeOptions = 30
    SequenceRNNOptions = 31
    StridedSliceOptions = 32
    ExpOptions = 33
    TopKV2Options = 34
    SplitOptions = 35
    LogSoftmaxOptions = 36
    CastOptions = 37
    DequantizeOptions = 38
    MaximumMinimumOptions = 39
    ArgMaxOptions = 40
    LessOptions = 41
    NegOptions = 42
    PadV2Options = 43
    GreaterOptions = 44
    GreaterEqualOptions = 45
    LessEqualOptions = 46
    SelectOptions = 47
    SliceOptions = 48
    TransposeConvOptions = 49
    SparseToDenseOptions = 50
    TileOptions = 51
    ExpandDimsOptions = 52
    EqualOptions = 53
    NotEqualOptions = 54
    ShapeOptions = 55
    PowOptions = 56
    ArgMinOptions = 57
    FakeQuantOptions = 58
    PackOptions = 59
    LogicalOrOptions = 60
    OneHotOptions = 61
    LogicalAndOptions = 62
    LogicalNotOptions = 63
    UnpackOptions = 64
    FloorDivOptions = 65
    SquareOptions = 66
    ZerosLikeOptions = 67
    FillOptions = 68
    BidirectionalSequenceLSTMOptions = 69
    BidirectionalSequenceRNNOptions = 70
    UnidirectionalSequenceLSTMOptions = 71
    FloorModOptions = 72
    RangeOptions = 73
    ResizeNearestNeighborOptions = 74
    LeakyReluOptions = 75
    SquaredDifferenceOptions = 76
    MirrorPadOptions = 77
    AbsOptions = 78
    SplitVOptions = 79
    UniqueOptions = 80
    ReverseV2Options = 81
    AddNOptions = 82
    GatherNdOptions = 83
    CosOptions = 84
    WhereOptions = 85
    RankOptions = 86
    ReverseSequenceOptions = 87
    MatrixDiagOptions = 88
    QuantizeOptions = 89
    MatrixSetDiagOptions = 90
    HardSwishOptions = 91
    IfOptions = 92
    WhileOptions = 93
    DepthToSpaceOptions = 94
    NonMaxSuppressionV4Options = 95
    NonMaxSuppressionV5Options = 96
    ScatterNdOptions = 97
    SelectV2Options = 98
    DensifyOptions = 99
    SegmentSumOptions = 100
    BatchMatMulOptions = 101
    CumsumOptions = 102
    CallOnceOptions = 103
    BroadcastToOptions = 104
    Rfft2dOptions = 105
    Conv3DOptions = 106
    HashtableOptions = 107
    HashtableFindOptions = 108
    HashtableImportOptions = 109
    HashtableSizeOptions = 110
    VarHandleOptions = 111
    ReadVariableOptions = 112
    AssignVariableOptions = 113
    RandomOptions = 114
    BucketizeOptions = 115
    GeluOptions = 116
    DynamicUpdateSliceOptions = 117
    UnsortedSegmentProdOptions = 118
    UnsortedSegmentMaxOptions = 119
    UnsortedSegmentMinOptions = 120
    UnsortedSegmentSumOptions = 121
    ATan2Options = 122
    SignOptions = 123
    BitcastOptions = 124
    BitwiseXorOptions = 125
    RightShiftOptions = 126
    RoPEOptions = 249
    RmsNormOptions = 250
    GRUOptions = 251
    BCQGatherOptions = 252
    BCQFullyConnectedOptions = 253
    InstanceNormOptions = 254

def BuiltinOptionsCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == BuiltinOptions().Conv2DOptions:
        import circle.Conv2DOptions
        return circle.Conv2DOptions.Conv2DOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().DepthwiseConv2DOptions:
        import circle.DepthwiseConv2DOptions
        return circle.DepthwiseConv2DOptions.DepthwiseConv2DOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ConcatEmbeddingsOptions:
        import circle.ConcatEmbeddingsOptions
        return circle.ConcatEmbeddingsOptions.ConcatEmbeddingsOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LSHProjectionOptions:
        import circle.LSHProjectionOptions
        return circle.LSHProjectionOptions.LSHProjectionOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().Pool2DOptions:
        import circle.Pool2DOptions
        return circle.Pool2DOptions.Pool2DOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SVDFOptions:
        import circle.SVDFOptions
        return circle.SVDFOptions.SVDFOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RNNOptions:
        import circle.RNNOptions
        return circle.RNNOptions.RNNOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().FullyConnectedOptions:
        import circle.FullyConnectedOptions
        return circle.FullyConnectedOptions.FullyConnectedOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SoftmaxOptions:
        import circle.SoftmaxOptions
        return circle.SoftmaxOptions.SoftmaxOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ConcatenationOptions:
        import circle.ConcatenationOptions
        return circle.ConcatenationOptions.ConcatenationOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().AddOptions:
        import circle.AddOptions
        return circle.AddOptions.AddOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().L2NormOptions:
        import circle.L2NormOptions
        return circle.L2NormOptions.L2NormOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LocalResponseNormalizationOptions:
        import circle.LocalResponseNormalizationOptions
        return circle.LocalResponseNormalizationOptions.LocalResponseNormalizationOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LSTMOptions:
        import circle.LSTMOptions
        return circle.LSTMOptions.LSTMOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ResizeBilinearOptions:
        import circle.ResizeBilinearOptions
        return circle.ResizeBilinearOptions.ResizeBilinearOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().CallOptions:
        import circle.CallOptions
        return circle.CallOptions.CallOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ReshapeOptions:
        import circle.ReshapeOptions
        return circle.ReshapeOptions.ReshapeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SkipGramOptions:
        import circle.SkipGramOptions
        return circle.SkipGramOptions.SkipGramOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SpaceToDepthOptions:
        import circle.SpaceToDepthOptions
        return circle.SpaceToDepthOptions.SpaceToDepthOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().EmbeddingLookupSparseOptions:
        import circle.EmbeddingLookupSparseOptions
        return circle.EmbeddingLookupSparseOptions.EmbeddingLookupSparseOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().MulOptions:
        import circle.MulOptions
        return circle.MulOptions.MulOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().PadOptions:
        import circle.PadOptions
        return circle.PadOptions.PadOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().GatherOptions:
        import circle.GatherOptions
        return circle.GatherOptions.GatherOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BatchToSpaceNDOptions:
        import circle.BatchToSpaceNDOptions
        return circle.BatchToSpaceNDOptions.BatchToSpaceNDOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SpaceToBatchNDOptions:
        import circle.SpaceToBatchNDOptions
        return circle.SpaceToBatchNDOptions.SpaceToBatchNDOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().TransposeOptions:
        import circle.TransposeOptions
        return circle.TransposeOptions.TransposeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ReducerOptions:
        import circle.ReducerOptions
        return circle.ReducerOptions.ReducerOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SubOptions:
        import circle.SubOptions
        return circle.SubOptions.SubOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().DivOptions:
        import circle.DivOptions
        return circle.DivOptions.DivOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SqueezeOptions:
        import circle.SqueezeOptions
        return circle.SqueezeOptions.SqueezeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SequenceRNNOptions:
        import circle.SequenceRNNOptions
        return circle.SequenceRNNOptions.SequenceRNNOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().StridedSliceOptions:
        import circle.StridedSliceOptions
        return circle.StridedSliceOptions.StridedSliceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ExpOptions:
        import circle.ExpOptions
        return circle.ExpOptions.ExpOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().TopKV2Options:
        import circle.TopKV2Options
        return circle.TopKV2Options.TopKV2OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SplitOptions:
        import circle.SplitOptions
        return circle.SplitOptions.SplitOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LogSoftmaxOptions:
        import circle.LogSoftmaxOptions
        return circle.LogSoftmaxOptions.LogSoftmaxOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().CastOptions:
        import circle.CastOptions
        return circle.CastOptions.CastOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().DequantizeOptions:
        import circle.DequantizeOptions
        return circle.DequantizeOptions.DequantizeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().MaximumMinimumOptions:
        import circle.MaximumMinimumOptions
        return circle.MaximumMinimumOptions.MaximumMinimumOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ArgMaxOptions:
        import circle.ArgMaxOptions
        return circle.ArgMaxOptions.ArgMaxOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LessOptions:
        import circle.LessOptions
        return circle.LessOptions.LessOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().NegOptions:
        import circle.NegOptions
        return circle.NegOptions.NegOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().PadV2Options:
        import circle.PadV2Options
        return circle.PadV2Options.PadV2OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().GreaterOptions:
        import circle.GreaterOptions
        return circle.GreaterOptions.GreaterOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().GreaterEqualOptions:
        import circle.GreaterEqualOptions
        return circle.GreaterEqualOptions.GreaterEqualOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LessEqualOptions:
        import circle.LessEqualOptions
        return circle.LessEqualOptions.LessEqualOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SelectOptions:
        import circle.SelectOptions
        return circle.SelectOptions.SelectOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SliceOptions:
        import circle.SliceOptions
        return circle.SliceOptions.SliceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().TransposeConvOptions:
        import circle.TransposeConvOptions
        return circle.TransposeConvOptions.TransposeConvOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SparseToDenseOptions:
        import circle.SparseToDenseOptions
        return circle.SparseToDenseOptions.SparseToDenseOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().TileOptions:
        import circle.TileOptions
        return circle.TileOptions.TileOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ExpandDimsOptions:
        import circle.ExpandDimsOptions
        return circle.ExpandDimsOptions.ExpandDimsOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().EqualOptions:
        import circle.EqualOptions
        return circle.EqualOptions.EqualOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().NotEqualOptions:
        import circle.NotEqualOptions
        return circle.NotEqualOptions.NotEqualOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ShapeOptions:
        import circle.ShapeOptions
        return circle.ShapeOptions.ShapeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().PowOptions:
        import circle.PowOptions
        return circle.PowOptions.PowOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ArgMinOptions:
        import circle.ArgMinOptions
        return circle.ArgMinOptions.ArgMinOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().FakeQuantOptions:
        import circle.FakeQuantOptions
        return circle.FakeQuantOptions.FakeQuantOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().PackOptions:
        import circle.PackOptions
        return circle.PackOptions.PackOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LogicalOrOptions:
        import circle.LogicalOrOptions
        return circle.LogicalOrOptions.LogicalOrOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().OneHotOptions:
        import circle.OneHotOptions
        return circle.OneHotOptions.OneHotOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LogicalAndOptions:
        import circle.LogicalAndOptions
        return circle.LogicalAndOptions.LogicalAndOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LogicalNotOptions:
        import circle.LogicalNotOptions
        return circle.LogicalNotOptions.LogicalNotOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UnpackOptions:
        import circle.UnpackOptions
        return circle.UnpackOptions.UnpackOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().FloorDivOptions:
        import circle.FloorDivOptions
        return circle.FloorDivOptions.FloorDivOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SquareOptions:
        import circle.SquareOptions
        return circle.SquareOptions.SquareOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ZerosLikeOptions:
        import circle.ZerosLikeOptions
        return circle.ZerosLikeOptions.ZerosLikeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().FillOptions:
        import circle.FillOptions
        return circle.FillOptions.FillOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BidirectionalSequenceLSTMOptions:
        import circle.BidirectionalSequenceLSTMOptions
        return circle.BidirectionalSequenceLSTMOptions.BidirectionalSequenceLSTMOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BidirectionalSequenceRNNOptions:
        import circle.BidirectionalSequenceRNNOptions
        return circle.BidirectionalSequenceRNNOptions.BidirectionalSequenceRNNOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UnidirectionalSequenceLSTMOptions:
        import circle.UnidirectionalSequenceLSTMOptions
        return circle.UnidirectionalSequenceLSTMOptions.UnidirectionalSequenceLSTMOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().FloorModOptions:
        import circle.FloorModOptions
        return circle.FloorModOptions.FloorModOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RangeOptions:
        import circle.RangeOptions
        return circle.RangeOptions.RangeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ResizeNearestNeighborOptions:
        import circle.ResizeNearestNeighborOptions
        return circle.ResizeNearestNeighborOptions.ResizeNearestNeighborOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().LeakyReluOptions:
        import circle.LeakyReluOptions
        return circle.LeakyReluOptions.LeakyReluOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SquaredDifferenceOptions:
        import circle.SquaredDifferenceOptions
        return circle.SquaredDifferenceOptions.SquaredDifferenceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().MirrorPadOptions:
        import circle.MirrorPadOptions
        return circle.MirrorPadOptions.MirrorPadOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().AbsOptions:
        import circle.AbsOptions
        return circle.AbsOptions.AbsOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SplitVOptions:
        import circle.SplitVOptions
        return circle.SplitVOptions.SplitVOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UniqueOptions:
        import circle.UniqueOptions
        return circle.UniqueOptions.UniqueOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ReverseV2Options:
        import circle.ReverseV2Options
        return circle.ReverseV2Options.ReverseV2OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().AddNOptions:
        import circle.AddNOptions
        return circle.AddNOptions.AddNOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().GatherNdOptions:
        import circle.GatherNdOptions
        return circle.GatherNdOptions.GatherNdOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().CosOptions:
        import circle.CosOptions
        return circle.CosOptions.CosOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().WhereOptions:
        import circle.WhereOptions
        return circle.WhereOptions.WhereOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RankOptions:
        import circle.RankOptions
        return circle.RankOptions.RankOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ReverseSequenceOptions:
        import circle.ReverseSequenceOptions
        return circle.ReverseSequenceOptions.ReverseSequenceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().MatrixDiagOptions:
        import circle.MatrixDiagOptions
        return circle.MatrixDiagOptions.MatrixDiagOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().QuantizeOptions:
        import circle.QuantizeOptions
        return circle.QuantizeOptions.QuantizeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().MatrixSetDiagOptions:
        import circle.MatrixSetDiagOptions
        return circle.MatrixSetDiagOptions.MatrixSetDiagOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().HardSwishOptions:
        import circle.HardSwishOptions
        return circle.HardSwishOptions.HardSwishOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().IfOptions:
        import circle.IfOptions
        return circle.IfOptions.IfOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().WhileOptions:
        import circle.WhileOptions
        return circle.WhileOptions.WhileOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().DepthToSpaceOptions:
        import circle.DepthToSpaceOptions
        return circle.DepthToSpaceOptions.DepthToSpaceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().NonMaxSuppressionV4Options:
        import circle.NonMaxSuppressionV4Options
        return circle.NonMaxSuppressionV4Options.NonMaxSuppressionV4OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().NonMaxSuppressionV5Options:
        import circle.NonMaxSuppressionV5Options
        return circle.NonMaxSuppressionV5Options.NonMaxSuppressionV5OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ScatterNdOptions:
        import circle.ScatterNdOptions
        return circle.ScatterNdOptions.ScatterNdOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SelectV2Options:
        import circle.SelectV2Options
        return circle.SelectV2Options.SelectV2OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().DensifyOptions:
        import circle.DensifyOptions
        return circle.DensifyOptions.DensifyOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SegmentSumOptions:
        import circle.SegmentSumOptions
        return circle.SegmentSumOptions.SegmentSumOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BatchMatMulOptions:
        import circle.BatchMatMulOptions
        return circle.BatchMatMulOptions.BatchMatMulOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().CumsumOptions:
        import circle.CumsumOptions
        return circle.CumsumOptions.CumsumOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().CallOnceOptions:
        import circle.CallOnceOptions
        return circle.CallOnceOptions.CallOnceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BroadcastToOptions:
        import circle.BroadcastToOptions
        return circle.BroadcastToOptions.BroadcastToOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().Rfft2dOptions:
        import circle.Rfft2dOptions
        return circle.Rfft2dOptions.Rfft2dOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().Conv3DOptions:
        import circle.Conv3DOptions
        return circle.Conv3DOptions.Conv3DOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().HashtableOptions:
        import circle.HashtableOptions
        return circle.HashtableOptions.HashtableOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().HashtableFindOptions:
        import circle.HashtableFindOptions
        return circle.HashtableFindOptions.HashtableFindOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().HashtableImportOptions:
        import circle.HashtableImportOptions
        return circle.HashtableImportOptions.HashtableImportOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().HashtableSizeOptions:
        import circle.HashtableSizeOptions
        return circle.HashtableSizeOptions.HashtableSizeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().VarHandleOptions:
        import circle.VarHandleOptions
        return circle.VarHandleOptions.VarHandleOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ReadVariableOptions:
        import circle.ReadVariableOptions
        return circle.ReadVariableOptions.ReadVariableOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().AssignVariableOptions:
        import circle.AssignVariableOptions
        return circle.AssignVariableOptions.AssignVariableOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RandomOptions:
        import circle.RandomOptions
        return circle.RandomOptions.RandomOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BucketizeOptions:
        import circle.BucketizeOptions
        return circle.BucketizeOptions.BucketizeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().GeluOptions:
        import circle.GeluOptions
        return circle.GeluOptions.GeluOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().DynamicUpdateSliceOptions:
        import circle.DynamicUpdateSliceOptions
        return circle.DynamicUpdateSliceOptions.DynamicUpdateSliceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UnsortedSegmentProdOptions:
        import circle.UnsortedSegmentProdOptions
        return circle.UnsortedSegmentProdOptions.UnsortedSegmentProdOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UnsortedSegmentMaxOptions:
        import circle.UnsortedSegmentMaxOptions
        return circle.UnsortedSegmentMaxOptions.UnsortedSegmentMaxOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UnsortedSegmentMinOptions:
        import circle.UnsortedSegmentMinOptions
        return circle.UnsortedSegmentMinOptions.UnsortedSegmentMinOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().UnsortedSegmentSumOptions:
        import circle.UnsortedSegmentSumOptions
        return circle.UnsortedSegmentSumOptions.UnsortedSegmentSumOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().ATan2Options:
        import circle.ATan2Options
        return circle.ATan2Options.ATan2OptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().SignOptions:
        import circle.SignOptions
        return circle.SignOptions.SignOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BitcastOptions:
        import circle.BitcastOptions
        return circle.BitcastOptions.BitcastOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BitwiseXorOptions:
        import circle.BitwiseXorOptions
        return circle.BitwiseXorOptions.BitwiseXorOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RightShiftOptions:
        import circle.RightShiftOptions
        return circle.RightShiftOptions.RightShiftOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RoPEOptions:
        import circle.RoPEOptions
        return circle.RoPEOptions.RoPEOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().RmsNormOptions:
        import circle.RmsNormOptions
        return circle.RmsNormOptions.RmsNormOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().GRUOptions:
        import circle.GRUOptions
        return circle.GRUOptions.GRUOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BCQGatherOptions:
        import circle.BCQGatherOptions
        return circle.BCQGatherOptions.BCQGatherOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().BCQFullyConnectedOptions:
        import circle.BCQFullyConnectedOptions
        return circle.BCQFullyConnectedOptions.BCQFullyConnectedOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions().InstanceNormOptions:
        import circle.InstanceNormOptions
        return circle.InstanceNormOptions.InstanceNormOptionsT.InitFromBuf(table.Bytes, table.Pos)
    return None
