# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MXQuantization(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MXQuantization()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMXQuantization(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MXQuantizationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x49\x52\x30", size_prefixed=size_prefixed)

    # MXQuantization
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MXQuantization
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MXQuantizationStart(builder):
    builder.StartObject(1)

def Start(builder):
    MXQuantizationStart(builder)

def MXQuantizationAddAxis(builder, axis):
    builder.PrependInt32Slot(0, axis, 0)

def AddAxis(builder, axis):
    MXQuantizationAddAxis(builder, axis)

def MXQuantizationEnd(builder):
    return builder.EndObject()

def End(builder):
    return MXQuantizationEnd(builder)


class MXQuantizationT(object):

    # MXQuantizationT
    def __init__(self):
        self.axis = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        mxquantization = MXQuantization()
        mxquantization.Init(buf, pos)
        return cls.InitFromObj(mxquantization)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, mxquantization):
        x = MXQuantizationT()
        x._UnPack(mxquantization)
        return x

    # MXQuantizationT
    def _UnPack(self, mxquantization):
        if mxquantization is None:
            return
        self.axis = mxquantization.Axis()

    # MXQuantizationT
    def Pack(self, builder):
        MXQuantizationStart(builder)
        MXQuantizationAddAxis(builder, self.axis)
        mxquantization = MXQuantizationEnd(builder)
        return mxquantization
