# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

class QuantizationDetails(object):
    NONE = 0
    CustomQuantization = 1
    MXQuantization = 2
    TRIXQuantization = 3

def QuantizationDetailsCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == QuantizationDetails().CustomQuantization:
        import circle.CustomQuantization
        return circle.CustomQuantization.CustomQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == QuantizationDetails().MXQuantization:
        import circle.MXQuantization
        return circle.MXQuantization.MXQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == QuantizationDetails().TRIXQuantization:
        import circle.TRIXQuantization
        return circle.TRIXQuantization.TRIXQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    return None
