# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TRIXQuantization(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TRIXQuantization()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTRIXQuantization(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TRIXQuantizationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x49\x52\x30", size_prefixed=size_prefixed)

    # TRIXQuantization
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TRIXQuantization
    def InChStride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TRIXQuantization
    def InputScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TRIXQuantization
    def InputZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TRIXQuantization
    def Offset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TRIXQuantization
    def OffsetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TRIXQuantization
    def OffsetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TRIXQuantization
    def OffsetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def TRIXQuantizationStart(builder):
    builder.StartObject(4)

def Start(builder):
    TRIXQuantizationStart(builder)

def TRIXQuantizationAddInChStride(builder, inChStride):
    builder.PrependInt32Slot(0, inChStride, 0)

def AddInChStride(builder, inChStride):
    TRIXQuantizationAddInChStride(builder, inChStride)

def TRIXQuantizationAddInputScale(builder, inputScale):
    builder.PrependFloat32Slot(1, inputScale, 0.0)

def AddInputScale(builder, inputScale):
    TRIXQuantizationAddInputScale(builder, inputScale)

def TRIXQuantizationAddInputZp(builder, inputZp):
    builder.PrependInt32Slot(2, inputZp, 0)

def AddInputZp(builder, inputZp):
    TRIXQuantizationAddInputZp(builder, inputZp)

def TRIXQuantizationAddOffset(builder, offset):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(offset), 0)

def AddOffset(builder, offset):
    TRIXQuantizationAddOffset(builder, offset)

def TRIXQuantizationStartOffsetVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOffsetVector(builder, numElems: int) -> int:
    return TRIXQuantizationStartOffsetVector(builder, numElems)

def TRIXQuantizationEnd(builder):
    return builder.EndObject()

def End(builder):
    return TRIXQuantizationEnd(builder)

try:
    from typing import List
except:
    pass

class TRIXQuantizationT(object):

    # TRIXQuantizationT
    def __init__(self):
        self.inChStride = 0  # type: int
        self.inputScale = 0.0  # type: float
        self.inputZp = 0  # type: int
        self.offset = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trixquantization = TRIXQuantization()
        trixquantization.Init(buf, pos)
        return cls.InitFromObj(trixquantization)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trixquantization):
        x = TRIXQuantizationT()
        x._UnPack(trixquantization)
        return x

    # TRIXQuantizationT
    def _UnPack(self, trixquantization):
        if trixquantization is None:
            return
        self.inChStride = trixquantization.InChStride()
        self.inputScale = trixquantization.InputScale()
        self.inputZp = trixquantization.InputZp()
        if not trixquantization.OffsetIsNone():
            if np is None:
                self.offset = []
                for i in range(trixquantization.OffsetLength()):
                    self.offset.append(trixquantization.Offset(i))
            else:
                self.offset = trixquantization.OffsetAsNumpy()

    # TRIXQuantizationT
    def Pack(self, builder):
        if self.offset is not None:
            if np is not None and type(self.offset) is np.ndarray:
                offset = builder.CreateNumpyVector(self.offset)
            else:
                TRIXQuantizationStartOffsetVector(builder, len(self.offset))
                for i in reversed(range(len(self.offset))):
                    builder.PrependInt32(self.offset[i])
                offset = builder.EndVector()
        TRIXQuantizationStart(builder)
        TRIXQuantizationAddInChStride(builder, self.inChStride)
        TRIXQuantizationAddInputScale(builder, self.inputScale)
        TRIXQuantizationAddInputZp(builder, self.inputZp)
        if self.offset is not None:
            TRIXQuantizationAddOffset(builder, offset)
        trixquantization = TRIXQuantizationEnd(builder)
        return trixquantization
