# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RoPEOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRoPEOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RoPEOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def RoPEOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x49\x52\x30", size_prefixed=size_prefixed)

    # RoPEOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RoPEOptions
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RoPEOptionsStart(builder): builder.StartObject(1)
def RoPEOptionsAddMode(builder, mode): builder.PrependInt32Slot(0, mode, 0)
def RoPEOptionsEnd(builder): return builder.EndObject()
